- block:
  - name: client | wait_for > NFS server to be up
    ansible.builtin.wait_for:
      timeout: 300
      port:    2049
      host:    "{{ item.server_host }}"
    with_items: "{{ nfs_imports }}"

  - ansible.builtin.set_fact:
      FSTYPE: "{{ nfs_only_v4 | bool | ternary('nfs4','nfs') }}"

  - name: client | mount > NFS shared directories
    ansible.posix.mount:
      name:   "{{ item.local_path }}"                           # create automatically the mount point directoy
      src:    "{{ item.server_host }}:{{ item.remote_path }}"
      fstype: "{{ FSTYPE }}"
      dump:   "{{ item.dump | default(omit) }}"
      opts:   "vers={{ nfs_version }},{{ item.opts | default(nfs_mount_opts) }}"
      passno: "{{ item.passno | default(omit) }}"
      state:  "{{ item.state | default('mounted') }}"
    with_items: "{{ nfs_imports }}"

  when: nfs_imports | length
  tags: nfs_client
