- block:
  - name: server | file > ensure directories to export exist
    ansible.builtin.file: # noqa 208
      path:  "{{ item.strip().split()[0] }}"
      state: directory
      owner: "{{ item.owner | default('nobody')  }}"
      group: "{{ item.group | default('nogroup') }}"
      mode:  0750
    with_items: "{{ nfs_exports }}"

  - name: server | template > generate exports file
    ansible.builtin.template:
      src:   exports
      dest:  /etc/exports
      owner: root
      group: root
      mode:  0640
    notify: "handlers | command > reload exportfs"

  when: nfs_exports | length
  tags: nfs_server
