- block:
  - name: services | ensure rpcbind is running as configured
    service:
      name:    rpcbind
      state:   "{{ nfs_rpcbind_state }}"
      enabled: "{{ nfs_rpcbind_enabled }}"
    when: ansible_distribution == "RedHat"

  - name: services | start and enable nfs server
    service:
      name:    "{{ nfs.server_daemon }}"
      state:   started
      enabled: yes
    when: nfs_exports | length

  tags: nfs_services
